version: "3.8"
services:

  app:
    build: .
    restart: always
    volumes:
      - .:/src
    command: uvicorn src.main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"

  database:
    image: postgres
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:latest
    container_name: redis_fastdb
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    environment:
      - REDIS-HOSTS=local:redis:6379
      - HTTP_USER=${HTTP_USER}
      - HTTP_PASSWORD=${HTTP_PASSWORD}
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  redis-data:
  pgdata: